### ISSUE TITLE
Crash on MC 1.18.1, also submitted to TKLib and Super Circuit Maker

### ISSUE THREAD

**Issue by Delta4Phoenix** [skiprocks999/Dynamic-Electricity#4] opened 2022-01-12 12:30 UTC
Exception in thread "main" java.lang.module.ResolutionException: Modules tklib and supercircuitmaker export package com.technicalitiesmc.lib to module dynamicelectricity
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

**Comment by skiprocks999** [comment] 2022-01-12 14:01
I need the following before I can do anything: 
A) Modlist
B) Whole log file

**Comment by amadornes** [comment] 2022-01-12 14:41
You don't have to worry about this one, it's got nothing to do with your mod. Feel free to close the issue.

As Player and I discovered when trying to set up the new ForgeCraft instance, this is caused by the Super Circuit Maker jar containing two mods, which is apparently not supported anymore these days, but for some reason it only crashes under some very specific conditions that we still don't understand (everyone else is running it just fine).

The latest version of SCM already split them off into two separate jars, so I'm suspecting they're running an older build.

Either way, I'm tracking it here: TechnicalitiesMC/SuperCircuitMaker#9

**Comment by skiprocks999** [comment] 2022-01-12 14:49
Alrighty thanks for the update

**Closed as completed by skiprocks999** 2022-01-12 14:49 UTC
